### PR TITLE
Leanne edit sidebar

### PR DESCRIPTION
**Pull request by Ltspringthorpe**
Let me know what you think and what needs to be different/fixed.

### CODE REVIEW

**Comment by Ltspringthorpe** [comment]
Let me know what you think and what needs to be different/fixed.

**Comment by salafrance** [comment]
reviewing, sorry about the delay

**Comment by salafrance** [comment]
hi Leanne - 

refactor looks nice, my concern with the edit panel is that it makes deleting features very awkward. Selecting a feature to delete means you first need to close the modal, and you can no longer select more than one feature at a time. An edit panel that didn't mask the sidebar would be more useful I think.

**Comment by salafrance** [comment]
You are also straddling github accounts, just so you know.

**Comment by Ltspringthorpe** [comment]
Hey Sarah, thanks for looking it over. You can still delete features
without closing the modal, but it's a bit hacky under the hood. Notice the
delete button at the bottom is usable. And I assumed that highlighting more
than one feature at a time was the desired functionality since the
material-ui table has been explicitly given the property
multiSelectable=false. Whoops.

A previous commit I made, a75fca6eeead21cf5782e959a6f4144daebf2b17, had the
edit panel not block anything, but I thought it didn't look as good. Take a
look at it if you'd like.

Oh dear god, I don't even know what straddling github accounts means. What
horrible thing have I done?

**Comment by salafrance** [comment]
you're logged in on two different accounts it looks like. It just makes bookkeeping kind of difficult.

**Pull request closed without merging**
